model_name: 'triplets_iou'
seed: 7
dataset_cls: 'RICOTripletsDataset'
dataset_config:
  triplets: 'pairs.json'
  only_data: True
  triplet_metric: 'iou'
  
dataloader_config:
  batch_size: 256
  collate_fn: 'pyg_triplets_data_collate'

trainer_config:
  max_epochs: 128

model_cls: 'LayoutGraphModelCNNNeuralRasterizer'
model_config:
  # Encoder (GNN) arguments
  label_embedding_dim: 64
  bbox_embedding_layer_dims:
    - 32
    - 64
  gnn_hidden_channels: 256
  gnn_out_channels: null
  gnn_num_layers: 4
  gnn_model_cls: 'GCN'
  use_edge_attr: False
  edge_label_embedding_dim: 16
  readout: 'global_mean_pool'
  # Decoder (CNN) arguments
  triplet_loss_margin: .5
  triplet_loss_distance_function: True
  reconstruction_loss_weight: 0.01
  # Optimizer parameters
  lr: 0.001